name: Tests
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install linux dependencies
        if: success()
        run: |
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
          sudo apt-get install ffmpeg
          sudo apt-get install libpulse-dev
          sudo apt-get install python3-pyaudio

      - name: Install python dependencies
        if: success()
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Run builder unit tests
        if: success()
        run: |
          python -m nose2 --start-dir .
